%----Creat the main figure----
hMainFigure = figure('Name', '参数设置', ...
    'NumberTitle', 'off', ...
    'Resize', 'on', ...
    'Units', 'pixel',...
    'HandleVisibility', 'callback',...
    'Position', [200 200 600 400], ...
    'menubar', 'none');
get(hMainFigure)